# AMLT: PangeaBench - baseline only (retry)
description: eval_pangeabench_baseline_retry

target:
  service: sing
  workspace_name: Workspace_NLC
  name: msrresrchbasicvc
  resource_group: gcr-singularity

environment:
  image: amlt-sing/acpt-torch2.7.1-py3.10-cuda12.6-ubuntu22.04
  setup:
  - echo "master_addr:" "$$MASTER_ADDR"
  - echo "master_port:" $$MASTER_PORT
  - echo "node_rank:" $$OMPI_COMM_WORLD_RANK
  - sudo apt update
  - sudo apt install -y tmux openjdk-17-jre-headless
  - sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
  - sudo chmod +x /usr/local/bin/yq

code:
  local_dir: /home/v-liyixia/CODES/VFA

storage:
  yixiali:
    storage_account_name: msranlpinternhot
    container_name: yixiali

jobs:
  - name: qwen25vl7b_instruct
    sku: 80G2-H100
    mpi: True
    sla_tier: standard
    priority: High
    command:
    - export WANDB_API_KEY=${WANDB_API_KEY}
    - export HF_TOKEN=${HF_TOKEN}
    - export HF_HOME=/tmp/hf_cache
    - export HF_HUB_CACHE=/tmp/hf_cache/hub
    - export HF_DATASETS_CACHE=/mnt/yixiali/CACHE/huggingface/datasets
    - export TRANSFORMERS_CACHE=/tmp/hf_cache/transformers
    - bash scripts/env_setup/uv_pangea.sh
    - source uv_pangea/bin/activate
    - export TASKS="maxm,cvqa,xgqa,xmmmu,xm100,marvl,m3exam"
    - bash scripts/eval/eval_pangeabench.sh /mnt/yixiali/MODELS/Qwen/Qwen2.5-VL-7B-Instruct /mnt/yixiali/CODES/VFA/outputs/eval_pangeabench/Qwen2.5-VL-7B-Instruct
