group: xm100_prism
task:
  - xm100_ar_prism
  - xm100_bn_prism
  - xm100_cs_prism
  - xm100_da_prism
  - xm100_de_prism
  - xm100_el_prism
  - xm100_en_prism
  - xm100_es_prism
  - xm100_fa_prism
  - xm100_fi_prism
  - xm100_fil_prism
  - xm100_fr_prism
  - xm100_he_prism
  - xm100_hi_prism
  - xm100_hr_prism
  - xm100_hu_prism
  - xm100_id_prism
  - xm100_it_prism
  - xm100_ja_prism
  - xm100_ko_prism
  - xm100_mi_prism
  - xm100_nl_prism
  - xm100_no_prism
  - xm100_pl_prism
  - xm100_pt_prism
  - xm100_quz_prism
  - xm100_ro_prism
  - xm100_ru_prism
  - xm100_sv_prism
  - xm100_sw_prism
  - xm100_te_prism
  - xm100_th_prism
  - xm100_tr_prism
  - xm100_uk_prism
  - xm100_vi_prism
  - xm100_zh_prism
